### ISSUE TITLE
Implement promise loop for index calculation

### ISSUE THREAD

**Issue by idea404** [idea404/near-trust-index#1]
Index calculation should go loop through all accounts in whitelist and query their respective functions to gather: 

1. number of NFTs issued, 
2. number of transactions with DAO.

and create a score based off these two results that has a max for each as to avoid score hacking.

**Comment by idea404** [comment]
How should the calculation handle when a whitelist contract function fails during the loop for every whitelisted contract for an account? Ignore? Fail the entire calculation and throw?

**Comment by sandoche** [comment]
`"kycdao.near": WhitelistTypes.DAO,`
Kycdao is not a dao it's a Soul bound token : Non Transferable NFT

**Comment by sandoche** [comment]
Send in the response the array of which one failed

**Comment by idea404** [comment]
Notes on how this should run: 

1. End user calls `call_method` to calculate index for a given `account_id`
2. Contract queries all whitelisted accounts and respective functions
3. Contract saves errors if any when fetching data from whitelist contracts into contract storage
4. Contract considers retrieved values and scores them according to a rubric for every whitelisted contract and function
5. Contract saves score for this `account_id` on the contract storage
6. Contract saves the timestamp for this `account_id` index calculation

The contract scores these values according to a rubric because otherwise the contract would have to also update all values for all other accounts before scoring them all relatively. Relative calculation would lead to `Exceeded prepaid gas` errors as computation time will exceed 300ms once there are enough whitelist contracts and/or accounts to take into consideration.

If an when this rubric is updated, the contract will have to recalculate all scores for all users. Either one by one, triggered by the contract owner, or all at once which will probably not work out because of the 300ms computation time limitation.

When the end user calls the `view_method`, the contract returns the score for the `account_id` alongside the missing whitelisted accounts it failed to fetch data from, and a timestamp for when the calculation was performed.

**Comment by sandoche** [comment]
@idea404 sounds good to me!

**Comment by idea404** [comment]
https://github.com/near/near-sdk-js/pull/309 <- update on how to do the syntax

**Comment by idea404** [comment]
Also, make sure to test how much TGAS is required for the view methods, this determines the max size for the whitelist

**Comment by idea404** [comment]
`calculate_index()` will return the

`{ account_id: account_id, index: this.accountIndexHistory.get(account_id), timestamp: this.accountIndexHistoryTimestamp.get(account_id), errors: [{"contract_id": "contract", "error_message": "errormessage"}, {...}, ...] }` if it succeeds,
 
  and if it fails it will return 
  
  `{"error": [{"contract_id": "contract", "error_message": "errormessage"}, {"contract_id": "contract", "error_message": "errormessage"}]}`
