### ISSUE TITLE
Check if cross contracts view calls cost gas fees

### ISSUE THREAD

**Issue by sandoche** [idea404/near-trust-index#4]
- If it cost gas
  - Keep it the way @idea404 did on [ed8926d](https://github.com/idea404/near-trust-index/commit/ed8926d4cff10bd3ca73a6ae125e9c2e20b0bacb) 
- If it doesn't
  - Let's remove `get_index_from_history` and make `get_index` a view function

**Comment by sandoche** [comment]
//

**Comment by idea404** [comment]
You can not run XCC without function calls, and thus not within `view` methods. See: https://github.com/idea404/xcc-view-test
